spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics

url-config:
  domain-name: localhost:8080